version: '3.8'

services:

  # Eureka Server
  eureka-server:
    build: ./discovery
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-net

  # Maintenance Service
  maintenance-service:
    build: ./maintenance
    container_name: maintenance-service
    ports:
      - "8070:8070"
    depends_on:
      - eureka-server
    networks:
      - microservices-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.10.161:3306/maintenance
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_RABBITMQ_HOST: 192.168.10.161

  # Surveillance Service
  surveillance-service:
    build: ./surveillance
    container_name: surveillance-service
    ports:
      - "8090:8090"
    depends_on:
      - eureka-server
    networks:
      - microservices-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.10.161:3306/surveillance
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_RABBITMQ_HOST: 192.168.10.161

networks:
  microservices-net:
    driver: bridge
